# fly.toml app configuration file generated for spring-rain-8267 on 2023-10-21T17:48:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-rain-8267"
primary_region = "arn"

[env]
  PORT = 3000

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
